# Generated by Django 2.1.4 on 2019-01-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
