# Generated by Django 2.1.4 on 2019-03-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=128)),
                ('pinpai', models.CharField(max_length=128)),
                ('ram', models.CharField(max_length=128)),
                ('cpu', models.CharField(max_length=128)),
                ('system_version', models.CharField(max_length=128)),
                ('holder_people', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '手机',
                'verbose_name_plural': '手机',
                'ordering': ['-pinpai'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
